export const MRT_STATIONS = [
  "Admiralty",
  "Aljunied",
  "Ang Mo Kio",
  "Bartley",
  "Bayfront",
  "Bayshore",
  "Beauty World",
  "Bedok",
  "Bedok North",
  "Bedok Reservoir",
  "Bencoolen",
  "Bendemeer",
  "Bishan",
  "Boon Keng",
  "Boon Lay",
  "Botanic Gardens",
  "Braddell",
  "Bras Basah",
  "Bright Hill",
  "Buangkok",
  "Bugis",
  "Bukit Batok",
  "Bukit Gombak",
  "Bukit Panjang",
  "Buona Vista",
  "Caldecott",
  "Canberra",
  "Cashew",
  "Changi Airport",
  "Chinatown",
  "Chinese Garden",
  "Choa Chu Kang",
  "City Hall",
  "Clarke Quay",
  "Clementi",
  "Commonwealth",
  "Dakota",
  "Dhoby Ghaut",
  "Dover",
  "Downtown",
  "Esplanade",
  "Eunos",
  "Expo",
  "Farrer Park",
  "Farrer Road",
  "Fort Canning",
  "Gardens by the Bay",
  "Geylang Bahru",
  "Great World",
  "Gul Circle",
  "HarbourFront",
  "Havelock",
  "Haw Par Villa",
  "Hillview",
  "Holland Village",
  "Hougang",
  "Hume",
  "Jalan Besar",
  "Joo Koon",
  "Jurong East",
  "Kaki Bukit",
  "Kallang",
  "Katong Park",
  "Kembangan",
  "Kent Ridge",
  "Khatib",
  "King Albert Park",
  "Kovan",
  "Kranji",
  "Labrador Park",
  "Lakeside",
  "Lavender",
  "Lentor",
  "Little India",
  "Lorong Chuan",
  "MacPherson",
  "Marina Bay",
  "Marina South Pier",
  "Marine Parade",
  "Marine Terrace",
  "Marsiling",
  "Marymount",
  "Mattar",
  "Maxwell",
  "Mayflower",
  "Mountbatten",
  "Napier",
  "Newton",
  "Nicoll Highway",
  "Novena",
  "one-north",
  "Orchard",
  "Orchard Boulevard",
  "Outram Park",
  "Pasir Panjang",
  "Pasir Ris",
  "Paya Lebar",
  "Pioneer",
  "Potong Pasir",
  "Promenade",
  "Punggol",
  "Punggol Coast",
  "Queenstown",
  "Raffles Place",
  "Redhill",
  "Rochor",
  "Sembawang",
  "Sengkang",
  "Serangoon",
  "Shenton Way",
  "Siglap",
  "Simei",
  "Sixth Avenue",
  "Somerset",
  "Springleaf",
  "Stadium",
  "Stevens",
  "Tai Seng",
  "Tampines",
  "Tampines East",
  "Tampines West",
  "Tan Kah Kee",
  "Tanah Merah",
  "Tanjong Katong",
  "Tanjong Pagar",
  "Tanjong Rhu",
  "Telok Ayer",
  "Telok Blangah",
  "Tiong Bahru",
  "Toa Payoh",
  "Tuas Crescent",
  "Tuas Link",
  "Tuas West Road",
  "Ubi",
  "Upper Changi",
  "Upper Thomson",
  "Woodlands",
  "Woodlands North",
  "Woodlands South",
  "Woodleigh",
  "Yew Tee",
  "Yio Chu Kang",
  "Yishun",
];
